# Generated by Django 3.1.3 on 2021-04-02 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accounts',
            name='credit',
            field=models.SmallIntegerField(default=0, verbose_name='学分'),
        ),
    ]
