# Generated by Django 3.1.3 on 2021-04-02 07:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BaseModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('last_mod_time', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('basemodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='interest.basemodel')),
                ('name', models.CharField(max_length=30, unique=True, verbose_name='标签名')),
            ],
            bases=('interest.basemodel',),
        ),
        migrations.CreateModel(
            name='InterestOrganization',
            fields=[
                ('basemodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='interest.basemodel')),
                ('name', models.CharField(max_length=32, verbose_name='兴趣圈名字')),
                ('title', models.TextField(verbose_name='简介')),
                ('status', models.CharField(choices=[('o', '正常'), ('d', '关闭'), ('s', '审核中')], default='s', max_length=1, verbose_name='状态')),
                ('create_account', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='创建者')),
            ],
            bases=('interest.basemodel',),
        ),
        migrations.CreateModel(
            name='Article',
            fields=[
                ('basemodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='interest.basemodel')),
                ('title', models.CharField(max_length=200, unique=True, verbose_name='标题')),
                ('body', models.TextField(verbose_name='正文')),
                ('comment_status', models.CharField(choices=[('o', '打开评论'), ('c', '关闭评论')], default='o', max_length=1, verbose_name='评论状态')),
                ('views', models.PositiveIntegerField(default=0, verbose_name='浏览量')),
                ('fabulous', models.PositiveIntegerField(default=0, verbose_name='点赞量')),
                ('status', models.CharField(choices=[('o', '正常'), ('d', '删除')], default='o', max_length=1, verbose_name='状态')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='作者')),
                ('tags', models.ManyToManyField(blank=True, to='interest.Tag', verbose_name='标签集合')),
            ],
            bases=('interest.basemodel',),
        ),
    ]
